# Generated by Django 3.2 on 2021-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=280)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[(1, 'Fashion'), (2, 'Toys'), (3, 'Homeware'), (4, 'Electronics')], max_length=64)),
            ],
        ),
    ]
