# Generated by Django 3.2 on 2021-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Fashion'), (2, 'Toys'), (3, 'Homeware'), (4, 'Electronics')], max_length=64),
        ),
    ]
